language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install python-twisted php-pear
# sequence of phpunit installation commands
  - sudo pear channel-discover pear.phpunit.de
  - sudo pear channel-discover pear.symfony-project.com
  - sudo pear channel-discover components.ez.no
  - sudo pear update-channels
  - sudo pear upgrade-all
  - sudo pear install --alldeps phpunit/PHPUnit
  - sudo pear install --force --alldeps phpunit/PHPUnit
install:
  - pip install -r requirements.txt --use-mirrors
before_script: ./run-service.py 12345 &
after_script: pkill -9 -f "run-service.py"
script:
  - ./test.sh
