language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install python-twisted php5
  - sudo curl -sS https://getcomposer.org/installer | sudo php
# sequence of phpunit installation commands
  - composer install phpunit/phpunit
#  - sudo pear channel-discover pear.phpunit.de
#  - sudo pear channel-discover pear.symfony-project.com
#  - sudo pear channel-discover components.ez.no
#  - sudo pear update-channels
#  - sudo pear upgrade-all
#  - sudo pear install --alldeps phpunit/PHPUnit
#  - sudo pear install --force --alldeps phpunit/PHPUnit
install:
  - pip install -r requirements.txt --use-mirrors
before_script:
  - source set_env.sh
  - ./run.py `echo $PYCACHED_PORT`
script:
  - ./test.sh
after_script:
  - ./stop.sh
