language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install php5 phpunit
install:
  - pip install -r requirements.txt --use-mirrors
before_script: ./server.py 12345 &
after_script: pkill -9 -f "server.py"
script:
  - cd client/php; phpunit; cd ../..
  - nosetests --nocapture